version: '3.8'

services:
  orderfox-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderfox-dev-container
    volumes:
      - ../:/workspaces/orderfox:cached
      - orderfox-node-modules:/workspaces/orderfox/frontend_vanilla/node_modules
      - orderfox-pip-cache:/root/.cache/pip
    ports:
      - "3000:3000"   # Frontend Vite dev server
      - "8000:8000"   # FastAPI Backend
      - "5678:5678"   # Python Debug Port
    environment:
      - NODE_ENV=development
      - DEVCONTAINER_MODE=true
      - PYTHONPATH=/workspaces/orderfox
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    networks:
      - orderfox-network
    working_dir: /workspaces/orderfox
    command: bash .devcontainer/docker-entrypoint.sh
    stdin_open: true
    tty: true

  # Firebase Emulator Suite (optional separate service)
  # firebase-emulators:
  #   image: node:18-alpine
  #   container_name: orderfox-firebase-emulators
  #   volumes:
  #     - ../:/workspaces/orderfox:cached
  #     - orderfox-firebase-cache:/root/.cache/firebase
  #   ports:
  #     - "4000:4000"   # Emulator Suite UI
  #     - "4001:4001"   # Auth Emulator
  #     - "4002:4002"   # Firestore Emulator
  #     - "4003:4003"   # Functions Emulator
  #     - "4004:4004"   # Hosting Emulator
  #     - "4005:4005"   # Pub/Sub Emulator
  #     - "4400:4400"   # Emulator Hub
  #   working_dir: /workspaces/orderfox
  #   command: |
  #     sh -c "
  #       npm install -g firebase-tools &&
  #       firebase emulators:start --only auth,firestore,functions,hosting,pubsub --host 0.0.0.0
  #     "
  #   networks:
  #     - orderfox-network
  #   depends_on:
  #     - orderfox-dev

volumes:
  orderfox-node-modules:
    name: orderfox-node-modules
  orderfox-pip-cache:
    name: orderfox-pip-cache

networks:
  orderfox-network:
    name: orderfox-network
    driver: bridge